### ISSUE TITLE
Add supermarket Gvirila

### ISSUE THREAD

**Issue by nermosh** [komachi/josm-ge-preset#10]
contact:email=Info@gvirila.com.ge
contact:facebook=https://www.facebook.com/Gvirila2022
contact:linkedin=https://www.linkedin.com/company/%E1%83%92%E1%83%95%E1%83%98%E1%83%A0%E1%83%98%E1%83%9A%E1%83%90-%E2%80%A2-gvirila/
name:en=Gvirila
name:ka=გვირილა
shop=supermarket

**Comment by empty-child** [comment]
Added
