### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by tsmock** [komachi/josm-ge-preset#13]
* https://wiki.openstreetmap.org/wiki/Tag:government=public_service needs to be properly documented (it returns a 404 HTTP response).
* https://wiki.openstreetmap.org/wiki/Tag:office%insurance should be https://wiki.openstreetmap.org/wiki/Tag:office%3Dinsurance

See https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/Georgia___https___github_com_komachi_josm_ge_preset_blob_main_ge_xml/ for details.

**Comment by komachi** [comment]
Thanks for reporting, fixed.
