### ISSUE TITLE
Please add Supermarket Zgapari

### ISSUE THREAD

**Issue by nermosh** [komachi/josm-ge-preset#4]
contact:email=info@zgapari.ge
contact:facebook=https://www.facebook.com/Zgaparisupermarket
contact:phone=+995322053800
contact:website=https://zgapari.ge
name:en=Zgapari
name:ka=ზღაპარი
shop=supermarket

**Comment by empty-child** [comment]
Uhm-m... We already have this network in preset

**Comment by nermosh** [comment]
Right. I forgot to switch between shops and food shops.
Sorry for inconvenience.
