### ISSUE TITLE
Carrefour_logo has been deleted on wikimedia commons

### ISSUE THREAD

**Issue by tsmock** [komachi/josm-ge-preset#48]
* https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/lastCompletedBuild/jdk=JDK8/testReport/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/Georgia___https___github_com_komachi_josm_ge_preset_blob_main_ge_xml/
* https://commons.wikimedia.org/wiki/File:Carrefour_logo.svg
* https://commons.wikimedia.org/wiki/Commons:Deletion_requests/Files_in_Category:Logos_of_Carrefour_Group

**Comment by empty-child** [comment]
Removed at all. Will be hosted here to avoid copyright issues for wikicommons
