### ISSUE TITLE
Missing icon: logos/pharmacies/pharmhouse.jpg

### ISSUE THREAD

**Issue by tsmock** [komachi/josm-ge-preset#61]
Specific message from [TaggingPresetPreferenceTestIT](https://josm.openstreetmap.de/jenkins/job/JOSM-Integration/10288/jdk=JDK11/testReport/junit/org.openstreetmap.josm.gui.preferences.map/TaggingPresetPreferenceTestIT/Georgia___https___github_com_komachi_josm_ge_preset_blob_main_ge_xml/):
> Georgia => [00352.186 W: [NODE, CLOSEDWAY, MULTIPOLYGON] Pharmhouse: Could not get presets icon https://raw.githubusercontent.com/komachi/josm-ge-preset/main/logos/pharmacies/pharmhouse.jpg] ==> expected: <true> but was: <false>

**Comment by empty-child** [comment]
File renamed (https://github.com/komachi/josm-ge-preset/pull/62)
